# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f9fbff85165b19bfddf82708b7b9f4e"
name = "BRK Apps (Agro)"
application_url = "https://localhost"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_discounts,read_validations,write_checkouts,write_discounts,write_validations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
